/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AmbientLightController: typeof import('./src/components/AmbientLightController.vue')['default']
    copy: typeof import('./src/components/SpotLightController copy.vue')['default']
    DirectLightController: typeof import('./src/components/DirectLightController.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    LightController: typeof import('./src/components/LightController.vue')['default']
    PointLightController: typeof import('./src/components/PointLightController.vue')['default']
    SpotLightController: typeof import('./src/components/SpotLightController.vue')['default']
  }
}
